### PR TITLE
Added an API to change the knot vectors

### PR DESCRIPTION
**Pull request by awernerdlr**
Hi,

i very much like the code I saw so far. Trying to contribute I added an Interface to manipulate the
knots vectors once the spline is already instantiated. This is useful for my usecase in which the
knots and coefficients are adapted in a regression like problem.
If you have any suggestions (remove changes which seem from to you), just ask.

### CODE REVIEW

**Comment by bgrimstad** [comment]
Hi @awernerdlr,

Thank you for your compliment and pull request, it is much appreciated. 

This is a useful feature and your code is clean so I would like to pull it. However, I will not pull it into our master branch as requested. Could you please prepare a pull request to the develop branch instead. 

May I also suggest that your remove the check_knots parameter from BSplineBasis1d::setKnotVector, as I believe that the knot vector should always be tested. In general it is useful to include a unit test (in this case for BSplineBasis1d::setKnotVector) and mimick the coding conventions of the code base.

I will proceed with closing this pull request.

Hope to hear from you soon. And feel free to discuss your application with us. It is always interesting to hear what people are using the library for.

Kind regards,

Bjarne

Note that we have done considerable work in the multidim-control-points branch which will be merged into develop soon. This will subsequently be merged into master when prepare the next release.

**Comment by bgrimstad** [comment]
Hi @awernerdlr,

Just checking in to hear if you have had any progress on this?

Bjarne

**Comment by awernerdlr** [comment]
Hi,
thanks for checking. I have done some work and don't want to hide it. I have ported this to new development branch. However I have not rebased onto your new commits (likely 2 month).
The code is also not split into pull requests yet. 

You can see the code on my fork: https://github.com/awernerdlr/splinter/tree/multidim-control-points
I also added functionality to compute partial derivatives in direction of the knot vectors.
I am pretty busy right now, probably it will take a while until i can split the changes into neat bits.

**Comment by bgrimstad** [comment]
It looks like you have done a lot of interesting work.

Give us a heads up when you are ready to create some pull requests!

**Pull request closed without merging**
