### PR TITLE
Support for Biicode (C++ dependency manager)

### PR DESCRIPTION
**Pull request by lasote**
Hi Bjarne!

My name is Luis Martinez and I write you from  **biicode** a small start-up that’s developing a C and C++ dependency manager; just like Maven and Maven Central for Java. Our tool aims to allow our users to set-up a project with just **#includes**. 

We took a look to multivariate-splines and realized it is pretty amazing. I have forked your repository to support biicode. Our CMakeLists.txt code is on a IF(BIICODE) block, so it not interfering if you want to compile it outside biicode.

We already have [**eigen** uploaded on biicode](http://www.biicode.com/eigen/eigen), so it's not necessary to take care about downloading, installing or building or find eigen package... just #include it.

I have tested it on Linux with GCC and OSX with Clang. On windows your last version doesn't compile with MinGW nor VisualStudio. That works for you on Windows? 

If you want to try it with biicode follow this steps:

1. Install biicode. https://www.biicode.com/downloads
2. Create new project folder and a block folder:

    $ bii init multivariate-splines
    $ cd multivariate-splines
    $ bii new lasote/multivariate-splines

3. Checkout the github repository in block folder:

    $ cd blocks/lasote/multivariate-splines
    $ git clone https://github.com/lasote/multivariate-splines.git . # Or your repo if you accept this PR
    $ bii cpp:build

The Biicode block is on lasote/multivariate-splines, but we will glad if you want to upload the library to your biicode's user.

If you would to do that, just rename block folder from "lasote" to your user, ex  "bgrimstad", and edit biicode.conf file and change the [parent] block (track from biicode remote) to **bgrimstad/multivariate-splines: -1**

This way biicode will publish a new block in your user workspace:

    $ bii publish --tag STABLE 

If you want to know more about biicode or need help just write me! lasote@gmail.com

Thanks Bjarne

### CODE REVIEW

**Comment by gablank** [comment]
Hello, Luis!

Thanks for the PR, this is interesting. Sorry for taking so long to get back to you, we have been very busy the past month and a half. I will take a look at it in the not too distant future.

Anders.

**Comment by lasote** [comment]
Hi Anders

 Ok!, Do not hesitate to ask me if you need some more information.

**Comment by gablank** [comment]
Hello again, Luis.

I have taken a look at Biicode, and it looks promising. I have a few questions, however:

1. We require Eigen version 3.2.3 for compiling with MSVC on Windows, but the newest version of Eigen that you host is Eigen version 3.2.2. Can we expect you to update projects in a timely manner, or will there be significant propagation delays from Eigen to your repository?

2. Do you have any infrastructure keeping track of the mapping from your version to the official versions of a project? F.ex. your version of Eigen is 4, whilst the Eigen version that represents is 3.2.2. I see you have written the version of Eigen under "Version", but that doesn't seem to be the case for other projects (like [SQlite3](https://www.biicode.com/sqlite/sqlite)).

3. Will we be able to output both dynamically and statically linked libraries with Biicode? By reading the docs I can find that "SET(BII_LIB_TYPE SHARED)" will set the library type to shared, but this seems to be a global variable and not tied to a particular library. The way we do it now is we output both dynamically and statically shared libraries when we compile.

4. When users want to use our library, how do they choose between linking dynamically and statically? As I understand it, you add "#include "bgrimstad/multivariate-splines"" or something along those lines, then execute "bii find". Biicode will then download the sources for our library and compile it, then link to it?

5. What exactly is a block? I haven't read the docs extensively, so I may have missed a part of the docs talking about it.


Thank you!

Anders.

**Comment by lasote** [comment]
Hi Anders!

Sorry for the delay answering, too many github notifications! First of all, thanks for taking a look at biicode, I'll try to answer your questions:

1. Yes, we will update Eigen asap, we are currently working on it. Now we are totally focused on user-support so if you need to add or update any library, we will help you. 

2. We use [version tags](http://docs.biicode.com/c++/publishing.html?highlight=tag#tag-a-version) to keep the relation between the original library version and version published in biicode. You can see an [example here](http://www.biicode.com/lasote/lasote/openssl/master/2). We uploaded Eigen a long time ago, in the update we are making we will tag it. 

3. (and 4) Yes, you can do it. When you SET(BII_LIB_TYPE SHARED) you are telling biicode to build the current block library as a shared library. The right way to do it is setting an option in cmake to control if it the library is shared or static. If other users depend on your library, they can change the value of this option changing the default behaviour. You can check (this)[http://docs.biicode.com/c++/building.html#overriding-dependencies-build-options-and-configuration] section of the docs.

4.  You can think about blocks as libraries or repositories. Biicode is a file-based dependency manager, this means that you can depend on a single file of a block (and biicode will download only its dependencies, not the whole block). It would be ideal that the blocks were small and with very specific functionality, so a library could be composed with several blocks. Historically C/C++ has HUGE libraries (boost, opencv...) and we think it's due to not having a dependency manager. We want to change this!! :D ... so, we thought "blocks" was a better fit for them than "libraries" or "repositories". It's a more "nuclear" concept.
(docs)[http://docs.biicode.com/c++/using_biicode/blocks.html]

**Comment by gablank** [comment]
Project seems dead, closing.

**Pull request closed without merging**
